name: Auto-generate War Report

on:
  schedule:
    # Runs every 30 mins
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run the report generator
        env:
          CR_API_KEY: ${{ secrets.CR_API_KEY }}
        run: python HTMLTest_v8.py

      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html
          # The following command will fail if there are no changes, preventing an empty commit.
          # The '|| exit 0' part ensures the workflow doesn't fail on no-changes.
          git commit -m "Auto-update war report: $(date)" || exit 0
          git push
